import { phone, BASE, SHOTS } from './lib.mjs';
const F = new URL('./files/', import.meta.url).pathname;
const { browser, page, errors } = await phone();
await page.goto(BASE + '#deal', { waitUntil: 'load' });
await page.waitForTimeout(500);
await page.setInputFiles('#om-file', F + (process.argv[2] || 'om-retail.pdf'));
await page.waitForSelector('#deal-tiles .tile', { timeout: 20000 });
await page.waitForTimeout(600);
const toast = await page.locator('.toast').allTextContents();
console.log('toast', toast);
const figs = await page.$$eval('ul.figs li', (lis) => lis.map((li) => [li.querySelector('label')?.textContent, li.querySelector('input')?.value, li.querySelector('.src')?.textContent]));
console.log('figures'); for (const f of figs) console.log('  ', JSON.stringify(f));
console.log('tiles', await page.$$eval('#deal-tiles .tile', (t) => t.map((x) => x.innerText.replace(/\n/g, ' | '))));
console.log('checks', await page.$$eval('#deal-checks li', (t) => t.map((x) => x.innerText)));
console.log('fin', await page.$$eval('#deal-fin-out li', (t) => t.map((x) => x.innerText.replace(/\n/g, ' '))));
console.log('rr', await page.$$eval('#deal-rr .tile', (t) => t.map((x) => x.innerText.replace(/\n/g, ' | '))));
console.log('questions', (await page.$$eval('#deal-q li', (t) => t.map((x) => x.innerText))).length);
const txt = await page.locator('#deal-root').innerText();
console.log('bad tokens', ['NaN', 'Infinity', 'undefined', 'null'].filter((w) => new RegExp(`\\b${w}\\b`).test(txt)));
await page.screenshot({ path: `${SHOTS}om-${process.argv[2] || 'retail'}.png`, fullPage: true });
console.log('scroll', await page.evaluate(() => [document.documentElement.scrollWidth, innerWidth]));
console.log('errors', errors);
await browser.close();
