import { phone, BASE, SHOTS } from './lib.mjs';
import fs from 'fs';
const F = new URL('./files/', import.meta.url).pathname;
const { browser, page, errors } = await phone();
const R = []; const check = (n, c, d = '') => R.push([c ? 'PASS' : 'FAIL', n, d]);
const sheetItem = (t) => page.locator('.action-sheet .action-item', { hasText: t }).first().click();
const upload = async (file) => {
  const [ch] = await Promise.all([page.waitForEvent('filechooser'), page.locator('#sheet-foot button', { hasText: 'Upload a template' }).click()]);
  await ch.setFiles(F + file);
};
await page.goto(BASE + '#deal', { waitUntil: 'load' });
await page.setInputFiles('#om-file', F + 'om-retail.pdf');
await page.waitForSelector('#deal-tiles .tile');
await page.click('#deal-root .view-head button[aria-label="More deal actions"]');
await sheetItem('Fill my Excel template');
await page.waitForSelector('#sheet-foot button:has-text("Upload a template")');
check('empty library explains itself', /No templates yet/.test(await page.textContent('#sheet-body')));
// an old .xls is refused with what to do
await upload('legacy.xls');
await page.waitForTimeout(500);
check('.xls refused with instructions', /save it as \.xlsx/i.test((await page.locator('.toast').allTextContents()).join(' ')));
await upload('uw-model.xlsx');
await page.waitForSelector('#sheet-body .tpl-grid');
const mapped = await page.$$eval('#sheet-body .map-row .h', (x) => x.map((h) => h.textContent));
const has = (label, cell) => mapped.some((m) => m.startsWith(label) && m.includes(`Inputs!${cell}`));
check('suggested: price → B5, NOI → B6, units → B8, SF → B9', has('Purchase / asking price', 'B5') && has('NOI (in place)', 'B6') && has('Units', 'B8') && has('Building SF', 'B9'), mapped.join(' | '));
check('suggested: interest rate by named range', has('Interest rate', 'B12'));
check('never suggested onto a formula (B7, B14)', !mapped.some((m) => /Inputs!B7\b|Inputs!B14\b/.test(m)));
check('rent roll table found on Rent Roll row 4', /row 4/.test(await page.textContent('#sheet-body')));
// map B13 (LTV) by hand: tap the cell
await page.locator('#sheet-body .tpl-cell[aria-label^="B13"]').click();
await sheetItem('Loan to value');
await page.waitForTimeout(200);
check('hand mapping shown on the grid', (await page.locator('#sheet-body .tpl-cell.mapped[aria-label^="B13"]').count()) === 1);
// tapping a formula cell explains, does not map
await page.locator('#sheet-body .tpl-cell[aria-label^="B7"]').click();
await page.waitForTimeout(200);
check('a formula cell cannot be mapped', /never overwritten/.test((await page.locator('.toast').allTextContents()).join(' ')));
await page.screenshot({ path: `${SHOTS}tpl-mapping.png` });
await page.locator('#sheet-foot button', { hasText: 'Save mapping' }).click();
await page.waitForTimeout(400);
// fill
await page.click('#deal-root .view-head button[aria-label="More deal actions"]');
await sheetItem('Fill my Excel template');
await page.waitForSelector('#sheet-body .li');
await page.locator('#sheet-body .li button', { hasText: 'Fill' }).first().click();
await page.waitForSelector('#sheet-body table.tpl-preview');
const prev = await page.$$eval('#sheet-body table.tpl-preview tr', (rows) => rows.map((r) => [...r.children].map((c) => c.textContent)));
const pRow = prev.find((r) => r[0] === 'Inputs!B5');
check('preview: B5 now $1,000,000 → $6,450,000, from OM p.2, read by formulas', pRow && pRow[2] === '1000000' && pRow[3] === '$6,450,000' && pRow[4] === 'OM page 2' && /formula/.test(pRow[5]), pRow && pRow.join(' | '));
check('preview lists the rent roll going in', /5 units go under the headings on Rent Roll/.test(await page.textContent('#sheet-body')));
const [dl] = await Promise.all([page.waitForEvent('download'), page.locator('#sheet-foot button', { hasText: 'Fill and download' }).click()]);
await dl.saveAs(F + 'out-uw-model.xlsx');
check('filled workbook downloaded as .xlsx', /\.xlsx$/.test(dl.suggestedFilename()), dl.suggestedFilename());
// versions: replace the file with the .xlsm twin
await page.click('#deal-root .view-head button[aria-label="More deal actions"]');
await sheetItem('Fill my Excel template');
await page.waitForSelector('#sheet-body .li');
await page.locator('#sheet-body .li button[aria-label^="More for"]').first().click();
const [ch2] = await Promise.all([page.waitForEvent('filechooser'), sheetItem('Replace the file')]);
await ch2.setFiles(F + 'uw-model.xlsm');
await page.waitForSelector('#sheet-body .tpl-grid');
check('macro workbook warned about', /macros/.test(await page.textContent('#sheet-body')));
await page.locator('#sheet-foot button', { hasText: 'Save mapping' }).click();
await page.waitForTimeout(300);
await page.click('#deal-root .view-head button[aria-label="More deal actions"]');
await sheetItem('Fill my Excel template');
await page.waitForSelector('#sheet-body .li');
check('library shows v2 of the template', /v2 · uw-model\.xlsm/.test(await page.textContent('#sheet-body .li')));
await page.locator('#sheet-body .li button', { hasText: 'Fill' }).first().click();
await page.waitForSelector('#sheet-body table.tpl-preview');
const [dl2] = await Promise.all([page.waitForEvent('download'), page.locator('#sheet-foot button', { hasText: 'Fill and download' }).click()]);
await dl2.saveAs(F + 'out-uw-model.xlsm');
check('macro workbook filled and kept as .xlsm', /\.xlsm$/.test(dl2.suggestedFilename()), dl2.suggestedFilename());
// export for a colleague, delete, import back
await page.click('#deal-root .view-head button[aria-label="More deal actions"]');
await sheetItem('Fill my Excel template');
await page.waitForSelector('#sheet-body .li');
await page.locator('#sheet-body .li button[aria-label^="More for"]').first().click();
const [dl3] = await Promise.all([page.waitForEvent('download'), sheetItem('Export for a colleague')]);
await dl3.saveAs(F + 'uw.template.json');
await page.locator('#sheet-body .li button[aria-label^="More for"]').first().click();
await sheetItem('Delete');
await page.waitForTimeout(400);
check('template deleted', /No templates yet/.test(await page.textContent('#sheet-body')));
const [ch3] = await Promise.all([page.waitForEvent('filechooser'), page.locator('#sheet-body button', { hasText: 'Import a template a colleague sent' }).click()]);
await ch3.setFiles(F + 'uw.template.json');
await page.waitForTimeout(800);
check('imported template keeps its mapping', /\d+ cells · 1 table/.test(await page.textContent('#sheet-body .li')), await page.textContent('#sheet-body .li'));
for (const [s, n, d] of R) console.log(s, '|', n, d ? `| ${d}` : '');
console.log('PASS', R.filter((x) => x[0] === 'PASS').length, 'FAIL', R.filter((x) => x[0] === 'FAIL').length, 'errors', errors);
await browser.close();
