import { phone, BASE, SHOTS } from './lib.mjs';
const F = new URL('./files/', import.meta.url).pathname;
const { browser, ctx, page, errors } = await phone();
await ctx.grantPermissions(['microphone']);
const R = []; const check = (n, c, d = '') => R.push([c ? 'PASS' : 'FAIL', n, d]);
const clickText = (t) => page.evaluate((t) => [...document.querySelectorAll('#deal-root button')].find((b) => b.textContent.includes(t)).click(), t);
await page.goto(BASE + '#deal', { waitUntil: 'load' });
await page.setInputFiles('#om-file', F + 'om-retail.pdf');
await page.waitForSelector('#tab-visit');
await page.click('#tab-visit');
await page.waitForSelector('#deal-audio');
await page.click('#rec-btn');
await page.waitForTimeout(2600);
check('record button shows a running clock', /Stop · 0:0[2-3]/.test(await page.textContent('#rec-btn')), await page.textContent('#rec-btn'));
await page.click('#rec-btn');
await page.waitForTimeout(800);
check('a recording is saved to the deal', (await page.locator('#deal-audio .voice-row').count()) === 1);
await page.setInputFiles('#audio-file', [F + 'memo.ogg', F + 'empty.m4a']);
await page.waitForTimeout(1200);
check('a Voice Memos file is added; an empty one skipped', (await page.locator('#deal-audio .voice-row').count()) === 2, JSON.stringify(await page.locator('.toast').allTextContents()));
check('duration read from the file', (await page.locator('#deal-audio .voice-row').nth(1).textContent()).includes('0:03'), await page.locator('#deal-audio .voice-row').nth(1).textContent());
const playable = await page.evaluate(async () => { const a = document.querySelectorAll('#deal-audio audio')[1]; try { await a.play(); a.pause(); return true; } catch (e) { return e.message; } });
check('the added file plays', playable === true, String(playable));
// start recording, switch to a new deal, stop: it belongs to the first deal
await page.click('#rec-btn');
await page.waitForTimeout(1200);
await clickText('All deals');
await page.waitForTimeout(300);
await clickText('Enter figures by hand');
await page.waitForTimeout(300);
await page.click('#tab-visit');
check('second deal has no voice notes', (await page.locator('#deal-audio .voice-row').count()) === 0);
await page.evaluate(() => [...document.querySelectorAll('#deal-root button')].find((b) => b.textContent.includes('All deals')).click());
await page.waitForTimeout(300);
await page.locator('#deal-root .list .li', { hasText: '4410' }).click();
await page.click('#tab-visit');
await page.waitForSelector('#rec-btn');
check('the first deal still shows its recording running', /Stop/.test(await page.textContent('#rec-btn')));
await page.click('#rec-btn');
await page.waitForTimeout(800);
check('the recording landed on the first deal', (await page.locator('#deal-audio .voice-row').count()) === 3);
await page.waitForTimeout(600);
await page.reload({ waitUntil: 'load' });
await page.waitForSelector('#tab-visit');
await page.click('#tab-visit');
await page.waitForSelector('#deal-audio');
check('voice notes persist after reload', (await page.locator('#deal-audio .voice-row').count()) === 3);
check('notes say they are not transcribed', /not transcribed/i.test(await page.textContent('#deal-audio')));
await page.locator('#deal-audio').screenshot({ path: `${SHOTS}voice.png` });
// delete + undo
await page.locator('#deal-audio .voice-row').first().locator('button').click();
await page.waitForTimeout(200);
check('delete a voice note', (await page.locator('#deal-audio .voice-row').count()) === 2);
await page.locator('.toast button').click();
await page.waitForTimeout(200);
check('undo restores it', (await page.locator('#deal-audio .voice-row').count()) === 3);
for (const [s, n, d] of R) console.log(s, '|', n, d ? `| ${d}` : '');
console.log('PASS', R.filter((x) => x[0] === 'PASS').length, 'FAIL', R.filter((x) => x[0] === 'FAIL').length, 'errors', errors);
await browser.close();
